import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";
import heroimg from "../../public/images/website/heroimg.svg";
import Features from "@/components/Features";
import SelfPublishingProcess from "@/components/SelfPublishingProcess";
import BookSection from "@/components/BookSection";
import Pricing from "@/components/Pricing";
import EbookSection from "@/components/EbookSection";
import BusinessStats from "@/components/BusinessStats";
import Network from "@/components/Network";
import FAQ from "@/components/FAQ";
import background from "../../public/images/website/background.jpg";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Yahashwin Publication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="text-gray-600 body-font mx-4 md:mx-8 lg:mx-32 mt-24"
         style={{
                  backgroundImage: `url(${background.src})`,
                  backgroundSize: 'cover',
                  backgroundPosition: 'center',
                  backgroundRepeat: 'no-repeat',
                }}>
          <div className="container mx-auto flex px-5 md:flex-row flex-col items-center">
            <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
              <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                Writing takes time, publishing with us does not!
              </h1>
              <p className="mb-8 font-semibold text-lg text-gray-400">
                Welcome to{" "}
                <span className="text-blue-900">Yahashwin Publication,</span>{" "}
                where stories come to life! Whether you are a seasoned author or
                an emerging voice, we are dedicated to turning your manuscript
                into a masterpiece. Join us, and let us create something
                extraordinary together.
              </p>
              <div className="flex justify-center">
                <button className="inline-flex items-center bg-blue-900 hover:bg-blue-800 text-white font-bold py-2 px-8 rounded-full">
                  Register
                  <svg
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    className="w-4 h-4 ml-1"
                    viewBox="0 0 24 24"
                  >
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </button>
              </div>
            </div>
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
              <Image
                className="object-cover object-center rounded"
                alt="hero"
                src={heroimg}
                width={500}
                height={500}
              />
            </div>
          </div>
        </section>

        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
          <path
            fill="#000b76"
            fill-opacity="1"
            d="M0,64L48,90.7C96,117,192,171,288,186.7C384,203,480,181,576,160C672,139,768,117,864,90.7C960,64,1056,32,1152,58.7C1248,85,1344,171,1392,213.3L1440,256L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
          ></path>
        </svg>
        <Features />
        <SelfPublishingProcess />
        <BookSection />
        <Pricing />
        <EbookSection />
        <Network />
        <BusinessStats />
        <FAQ />
      </main>
    </>
  );
}
